// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ySm9U55qaKta-UOvvK3mDr8yNfJudt0',
    appId: '1:280578944842:web:717a6184419c889ea7dbb3',
    messagingSenderId: '280578944842',
    projectId: 'artiq-1ebb2',
    authDomain: 'artiq-1ebb2.firebaseapp.com',
    storageBucket: 'artiq-1ebb2.firebasestorage.app',
    measurementId: 'G-MFZ2Z21SSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ySm9U55qaKta-UOvvK3mDr8yNfJudt0',
    appId: '1:280578944842:android:717a6184419c889ea7dbb3',
    messagingSenderId: '280578944842',
    projectId: 'artiq-1ebb2',
    authDomain: 'artiq-1ebb2.firebaseapp.com',
    storageBucket: 'artiq-1ebb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ySm9U55qaKta-UOvvK3mDr8yNfJudt0',
    appId: '1:280578944842:ios:717a6184419c889ea7dbb3',
    messagingSenderId: '280578944842',
    projectId: 'artiq-1ebb2',
    authDomain: 'artiq-1ebb2.firebaseapp.com',
    storageBucket: 'artiq-1ebb2.firebasestorage.app',
    iosBundleId: 'com.artiq.artiqFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ySm9U55qaKta-UOvvK3mDr8yNfJudt0',
    appId: '1:280578944842:ios:717a6184419c889ea7dbb3',
    messagingSenderId: '280578944842',
    projectId: 'artiq-1ebb2',
    authDomain: 'artiq-1ebb2.firebaseapp.com',
    storageBucket: 'artiq-1ebb2.firebasestorage.app',
    iosBundleId: 'com.artiq.artiqFlutter',
  );
}
